const text = [ 
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut ullamcorper nulla. Proin tincidunt dictum gravida. Nam tempor, dui eget tempor convallis, diam mi sagittis ex, ut lobortis magna dui vel massa. Fusce vitae accumsan mi. Quisque feugiat ex sit amet orci dignissim egestas. Donec a venenatis odio, vitae pellentesque dolor. Aliquam lobortis nisl in leo volutpat varius. Vestibulum venenatis lorem a scelerisque ullamcorper. Phasellus et massa in metus gravida ultrices a placerat nibh.`,
    `Curabitur congue elit risus, vel ultricies felis laoreet a. Nullam et elementum libero. In dictum, odio a venenatis congue, felis neque dignissim ipsum, eget tincidunt diam arcu a justo. Nam ac interdum tortor. In ultricies arcu nec faucibus vulputate. Nulla egestas rhoncus est, vel eleifend lectus blandit iaculis. Integer arcu tortor, iaculis sit amet luctus id, scelerisque a mauris. Vestibulum a neque a augue feugiat commodo. Suspendisse malesuada turpis orci, vitae condimentum nunc ultrices et. Phasellus ornare, justo id interdum faucibus, est elit eleifend enim, et euismod felis turpis sit amet metus. Etiam urna nulla, convallis id tempor maximus, accumsan id dui. Nunc suscipit ipsum ut pulvinar vulputate. Nullam at tincidunt nisl. Sed pretium dui orci, vitae sagittis nulla vehicula sed. Donec orci est, congue quis diam quis, mattis tincidunt nunc. Sed est ex, sodales vitae elementum vel, hendrerit in lectus.`,
    `Morbi placerat vestibulum augue eget interdum. Ut eu justo vel quam posuere vehicula molestie eu turpis. Suspendisse eget fringilla leo, vel mollis augue. Duis bibendum cursus magna at aliquet. Morbi maximus nulla a orci fringilla aliquam. Donec eget purus eget ex scelerisque semper ac ac nibh. Praesent sed leo nunc. Suspendisse posuere, purus non tempor varius, neque nibh efficitur ex, at condimentum sem lorem nec est. Nunc porta accumsan quam, et sodales purus dictum a. Praesent auctor libero eget odio faucibus convallis. Praesent non facilisis velit. Nullam purus nulla, aliquet id eros sit amet, ultricies posuere ligula. Etiam interdum a leo sit amet lacinia. Sed ut metus a ligula facilisis scelerisque et sit amet magna. Aliquam erat volutpat.`,
    `Nunc mollis libero mauris, id aliquam erat gravida vel. Etiam volutpat iaculis ultrices. Donec pretium, ante volutpat euismod mattis, massa quam egestas ipsum, in blandit ipsum eros nec metus. Sed scelerisque massa sagittis, aliquet nulla at, efficitur lectus. Donec tempor volutpat leo, in ultrices risus sodales in. Aenean efficitur commodo condimentum. Sed at justo et risus commodo hendrerit in nec lorem. Aenean euismod erat non scelerisque convallis. Duis et euismod eros.`,
    `Fusce sagittis enim vel mattis malesuada. Curabitur sed semper metus, aliquet lobortis quam. Nam porta dolor lorem, et ultrices lorem scelerisque sed. Nunc arcu tortor, auctor in tellus sit amet, accumsan volutpat orci. Integer tristique ligula eu enim imperdiet tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam erat volutpat.`,
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id malesuada metus. Integer ligula elit, auctor placerat lacus non, condimentum tristique lectus. Suspendisse et lorem sed mi varius malesuada non eu dolor. Morbi in nisl ut nunc ultricies laoreet. Aenean volutpat arcu eget enim iaculis, et aliquet urna viverra. In venenatis purus non ex varius, vitae tristique turpis congue. Phasellus maximus pharetra hendrerit. Fusce porta sagittis justo, sed dignissim lacus varius in.`,
    `Curabitur elementum, eros et luctus dapibus, felis tellus consectetur quam, laoreet faucibus lorem est eget nisl. Maecenas dignissim commodo facilisis. Etiam id eros non tellus convallis auctor vitae sed lacus. Maecenas eget dui finibus sem blandit elementum. Nulla venenatis ut justo eu tristique. Maecenas nec quam tortor. Ut pellentesque non sem in iaculis. Nam nisl elit, venenatis eu ligula ut, pharetra mattis mi. Donec feugiat feugiat erat sit amet lacinia. Nulla nec consectetur sem, sit amet molestie ipsum. Nulla ac metus nec odio fermentum egestas. Duis pharetra ac magna at fermentum. Integer quis dictum nulla.`,
    `Donec condimentum non nisi sed pellentesque. Mauris ut sapien vitae nulla condimentum aliquet vitae in justo. Donec condimentum dolor non ante suscipit, ut sagittis purus placerat. Curabitur et mi eu elit pharetra consequat quis non turpis. Pellentesque aliquet suscipit elit at laoreet. Mauris quis ornare odio. Quisque orci mi, pulvinar eu euismod nec, consectetur non libero. Sed venenatis mauris ut vulputate vulputate. Phasellus feugiat interdum mauris. Quisque quis orci auctor, auctor ante id, volutpat orci.`,
    `Mauris dignissim ex vel ornare ornare. Etiam arcu tortor, fringilla ac varius sed, eleifend quis purus. Nullam ac justo purus. Vivamus diam justo, sagittis et facilisis sed, venenatis vel purus. Quisque commodo, elit sit amet bibendum convallis, ipsum ex congue urna, eu condimentum dolor purus eget lacus. Nulla laoreet viverra lacus, quis fermentum magna bibendum nec. Vestibulum ullamcorper elit sit amet urna congue tempor. Vestibulum vestibulum sodales augue, ut sodales leo tempus eu. Donec ipsum felis, maximus vitae nunc sed, eleifend imperdiet velit. Ut efficitur lacus sem, vel condimentum nunc sodales quis. Nulla condimentum diam eu dolor scelerisque pellentesque. Integer id fringilla arcu.`,
    `Maecenas at bibendum mi. Etiam mauris enim, mattis a nisl non, dictum varius dui. Fusce tincidunt massa sed mauris placerat, quis porttitor velit rhoncus. Aliquam ac suscipit nisl, pharetra pharetra magna. Etiam sem sapien, ullamcorper at enim in, fermentum lacinia urna. Sed id sem dapibus, posuere enim vitae, tristique purus. Maecenas ac mi neque. Vestibulum in viverra enim, a facilisis quam.`,
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mollis finibus diam et faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam malesuada tristique erat pellentesque commodo. Ut efficitur metus ut velit venenatis, sed mollis lacus luctus. Nunc consequat enim dapibus egestas efficitur. Vivamus ut eros nec ipsum suscipit imperdiet sit amet id augue. Etiam tempor et ipsum congue molestie. Fusce a sapien dolor. Aliquam eu ultrices leo, et porta augue. Mauris enim urna, feugiat id tincidunt in, scelerisque in nisi. In in nulla sodales, aliquam neque ut, mattis purus. In facilisis sem et arcu ultricies, et facilisis orci rutrum. Vivamus auctor lorem vel ligula facilisis, nec semper nisl fringilla. Vestibulum odio risus, posuere nec mollis quis, laoreet quis ipsum. Nam imperdiet erat sit amet metus facilisis, a fringilla nibh lobortis.`,
    `Sed ullamcorper odio ut turpis tempus hendrerit. Nulla dapibus dolor dignissim purus luctus accumsan. Donec rhoncus, orci in bibendum volutpat, elit sem facilisis lorem, ut tincidunt est felis id sem. Ut gravida lacus id eros convallis rutrum. Fusce ut lectus vel elit fermentum pretium non id nunc. Donec lobortis ligula ligula. Nulla non tincidunt nibh. Donec ac viverra mi. Phasellus porta nisl vel ligula consectetur, at cursus ante finibus. In quis orci id libero commodo dignissim. Mauris ante nisl, fringilla quis aliquam sed, molestie sed neque. Vivamus placerat tristique purus nec interdum. Proin justo urna, tincidunt a lacinia eu, venenatis ut magna. Nulla varius lacinia consequat.`,
    `Donec scelerisque lectus in erat fringilla finibus quis in tellus. Ut non nulla semper, varius libero convallis, scelerisque purus. Morbi lorem diam, finibus non arcu eu, congue semper purus. Aliquam convallis lacus ligula, vitae auctor lorem ultricies eget. Aenean viverra cursus vestibulum. Cras sollicitudin cursus semper. Maecenas tristique dui tincidunt turpis maximus, id rhoncus massa scelerisque.`,
    `Sed id est ultrices, volutpat mi eget, varius ipsum. Donec in facilisis diam. Donec finibus orci vitae nibh condimentum egestas. In eget turpis a dolor tempor auctor. Quisque tincidunt leo sit amet neque sagittis, non eleifend tellus dapibus. Vivamus venenatis efficitur placerat. Etiam sed tellus lacus. Aenean volutpat auctor ex sed consectetur. Morbi nec metus eu nunc porta tincidunt sed pellentesque dui. Etiam molestie ornare nunc, at aliquet lectus suscipit sit amet.`,
    `Nulla facilisi. Nullam ut diam sed ex gravida semper. Nam pulvinar placerat velit, sit amet dictum lectus lobortis ac. Duis id bibendum libero. Etiam vel est velit. Integer sagittis mi metus, id ullamcorper nulla vulputate sed. Nulla vestibulum luctus vulputate. Vestibulum faucibus justo sit amet metus vestibulum auctor. Nam condimentum finibus magna gravida elementum. Etiam augue quam, molestie eget luctus ac, rhoncus id arcu. Nulla gravida porta dignissim. Donec gravida lacus et tortor congue, nec dictum lectus aliquet. Etiam nulla ante, sagittis ac auctor dapibus, cursus at nunc. In iaculis ac quam porttitor posuere. Pellentesque sit amet vulputate nunc, sed condimentum velit. Donec non mi vitae mi egestas scelerisque.`,
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dictum pharetra quam, vitae eleifend dolor scelerisque quis. Nulla rutrum magna sit amet tortor placerat pulvinar. Praesent vehicula, massa posuere auctor condimentum, nunc orci fringilla augue, ac varius ligula mauris id arcu. Proin et euismod erat. Vivamus vel turpis quis massa semper congue sit amet eget turpis. Ut iaculis at nisl quis lobortis. Aenean condimentum odio eros, ac rhoncus enim finibus a. Morbi ornare nisi nisl, ut tincidunt ligula lobortis at. Mauris ac posuere sapien, quis egestas massa. Nullam ac nisl sagittis, aliquet enim id, cursus eros. Mauris mi metus, gravida sed accumsan ut, consectetur eget enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam iaculis venenatis bibendum. Nunc vel suscipit justo, nec sagittis est. Cras lobortis lorem accumsan gravida ultricies.`,
    `Nunc facilisis eros eu lorem euismod mollis a a ligula. Aenean ut mi eu dolor tempor scelerisque vel non justo. Donec et ullamcorper purus. Ut sem velit, condimentum eu leo sed, viverra rhoncus felis. Etiam sed sem fermentum, tristique felis congue, condimentum dolor. Cras mattis pretium mattis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam dictum arcu ut felis suscipit imperdiet. Vestibulum eget lorem placerat, interdum lorem id, elementum felis. Phasellus ac interdum justo, vel luctus est. Sed auctor, nibh tempus cursus elementum, leo eros posuere lectus, vel viverra dui nibh at massa. Quisque luctus efficitur congue. Praesent ac lectus at ex porta sodales. Sed feugiat, nisi ut ultricies condimentum, metus dui iaculis mauris, sed fringilla ipsum urna nec nibh. Integer augue mauris, cursus vel velit nec, auctor porta lacus.`,
    `Curabitur turpis augue, suscipit at tristique eget, dignissim nec odio. Ut vitae vulputate ex. Fusce sit amet risus sit amet neque dignissim condimentum eu vel ligula. Nunc facilisis tempus nibh, in ultricies est feugiat non. Aenean vitae dolor ut mi aliquam elementum vel id urna. Praesent vestibulum est purus, at tempor velit auctor quis. Integer pretium orci sed lacinia ornare. Vivamus suscipit ligula nec metus malesuada vestibulum quis nec turpis. Fusce blandit laoreet tincidunt. Pellentesque ornare cursus dolor, nec varius nunc dictum at. In laoreet sem et posuere suscipit.`,
    `Proin sit amet neque lorem. Ut blandit arcu vel ornare iaculis. Vestibulum vestibulum odio metus, at dignissim nulla mattis vitae. Cras lacus felis, euismod quis lacinia sed, interdum id tortor. Suspendisse scelerisque, purus eu mattis dignissim, ligula risus mollis tortor, eget commodo tortor nibh in augue. Morbi eget diam blandit, ultrices ex sit amet, pellentesque nisl. Maecenas sit amet arcu vitae erat malesuada pretium. Quisque gravida eu erat eu lacinia. Proin magna nisi, efficitur a libero in, vestibulum elementum dolor.`,
    `Proin neque nunc, efficitur eget consequat ac, elementum non urna. Donec justo neque, condimentum in diam eget, blandit eleifend velit. Fusce rhoncus, massa eget ornare feugiat, erat orci consectetur augue, ut porttitor enim odio ac arcu. Vestibulum sed pharetra dolor. Nulla facilisi. Sed id lacus nisl. Nullam a neque quis velit semper consequat. Nam sagittis magna nec ultrices varius. Quisque semper magna interdum lacus rhoncus, ac tristique felis volutpat. Pellentesque pharetra auctor nunc, interdum sagittis magna dictum ac. Aliquam in convallis enim. Integer neque libero, hendrerit ut molestie et, posuere et eros. Nullam vel urna purus. Nunc pretium fermentum risus. Maecenas at risus nisi.`,
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu auctor lorem. Vestibulum quis ipsum sollicitudin, elementum mi at, interdum tellus. Phasellus ut nulla eget purus finibus dignissim quis vitae sapien. Integer nec ipsum euismod, lobortis magna ac, rhoncus diam. Sed gravida nisi vel justo imperdiet blandit. Sed posuere aliquam lorem, at ultrices odio commodo eu. Sed felis lorem, molestie vitae nibh in, placerat pulvinar nisi. Maecenas efficitur tincidunt sem id convallis. Etiam mollis fermentum ullamcorper. Maecenas ut dui ultrices, luctus urna in, finibus ipsum. Aenean posuere velit at diam consectetur, sit amet dictum quam pulvinar. Suspendisse pulvinar elit et tincidunt semper. Aliquam ultrices tincidunt orci in pretium. Nunc congue eros sed ornare posuere. Vestibulum blandit quam eu justo tincidunt, vitae porttitor quam rhoncus.`,
    `Nam euismod ultrices lectus, quis rutrum velit accumsan non. Nam in leo nec augue lacinia interdum ut sit amet dui. Pellentesque suscipit dictum metus nec commodo. Integer pharetra lectus risus. Etiam id viverra augue. Duis eu interdum dui. Donec a dolor tortor. Nam posuere enim eget tellus porttitor, et sagittis purus posuere. Suspendisse at posuere metus, eget pretium tellus. Donec pellentesque tristique orci et congue. Pellentesque odio lorem, consectetur at laoreet ac, gravida eu felis. Nulla placerat dictum sollicitudin. Integer faucibus nunc eu quam posuere iaculis.`,
    `Phasellus elementum velit vitae nisi posuere vehicula. Donec id mollis risus, quis tempus mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc semper tincidunt mauris, fermentum feugiat libero molestie eget. Ut commodo diam a pellentesque tempor. Ut mollis, sapien in eleifend suscipit, ante mi tincidunt sem, rhoncus volutpat neque velit ac lectus. Fusce sed arcu a tellus ultricies porta maximus in massa. Praesent pretium volutpat finibus. Nulla ullamcorper est imperdiet urna consequat efficitur. Etiam ut tempus sapien, ut porttitor felis. Maecenas in suscipit magna. Aenean et dolor ut orci consequat ultricies.`,
    `Integer in leo faucibus, luctus velit eu, venenatis nibh. Ut nec orci vitae erat maximus elementum id ac mi. Curabitur efficitur diam sit amet arcu condimentum consequat. Sed quis ligula metus. Curabitur tristique congue diam, id porttitor dui molestie eget. Aliquam ut tempus quam. Nulla purus magna, varius sed pulvinar nec, sagittis in metus. Aenean ullamcorper dolor id tellus dapibus, at volutpat quam euismod. Integer luctus viverra faucibus. Sed at odio fermentum, efficitur massa id, luctus quam. Nulla vestibulum vulputate massa, a accumsan sem tempus id.`,
    `Nullam sollicitudin id nisl vitae condimentum. Nulla vulputate commodo blandit. Aliquam vel lacus dolor. Proin eget massa nulla. Aliquam erat volutpat. Fusce accumsan semper egestas. Pellentesque nec vehicula mauris, tristique pretium eros. Curabitur gravida enim eget leo ullamcorper, et pretium erat lacinia.`
];
const DisplayTxt = "This website is a paragraph generator for testing code etc...";
const quickbrownfox = "The quick brown fox jumped over the lazy dogs";

const form = document.querySelector('.lorem-form');
const amount = document.getElementById('amount');
const result = document.querySelector('.lorem-text');

result.innerHTML = `<p class="result">${DisplayTxt}<br><br>${quickbrownfox}</p>`;


form.addEventListener('submit', function(e){
    e.preventDefault();
    const value = parseInt(amount.value);
    const random = Math.floor(Math.random() * text.length)
    
    if(isNaN(value) || value <= 0 || value > text.length){
        result.innerHTML = `<p class="result">${text[random]}</p>`;
    }
    else{
        let temptext = text.slice(0,value);
        temptext = temptext.map(function(item){
            return `<p class="result">${item}</p>`;
        })
        .join("");
    result.innerHTML = temptext;
    }
})